#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpackage remove deno"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  deno::remove
}

run() {
  core $@
}

run $@
